language: python
cache: pip
dist: xenial

install:
  - pip install --upgrade pip
  - pip install --upgrade setuptools pipenv
<<<<<<< HEAD
  - pip install -r dev-requirements.txt
=======
  - pip install -r dev-requiements.txt
>>>>>>> ca901e6d60f14b6727eb3ea687e8c0fb08820325

matrix:
  include:
  - name: "Lint and static analysis"
    python: "3.6"
    script:
      - ./scripts/copyright_line_check.sh
      - pylint --rcfile=.pylintrc bubs
  - name: "Python 3.6 unit tests"
    python: "3.6"
    script:
      - pytest --cov=bubs bubs
  - name: "Python 3.7 unit tests"
    python: "3.7"
    script:
      - pytest --cov=bubs bubs
after_success:
  - coveralls
