language: python
cache: pip
dist: xenial

install:
  - pip install --upgrade pip
  - pip install --upgrade setuptools pipenv
  - pip install -r dev-requirements.txt

matrix:
  include:
  - name: "Lint and static analysis"
    python: "3.6"
    script:
      - ./scripts/copyright_line_check.sh
      - pylint --rcfile=.pylintrc bubs
      - pydocstyle --config=.pydocstyle_test bubs
      - pydocstyle --config=.pydocstyle bubs
  - name: "Python 3.6 unit tests"
    python: "3.6"
    script:
      - pytest --cov=bubs bubs
after_success:
  - coveralls
